#
# Module manifest for module 'AER'
#
# Generated by: Henderson Andrade (GitHub: @hendersonandrade) | Henrique Mizael (GitHub: @hmizael) | github.com/TrimTechBR, trimtech.github.io
#
# Generated on: 28/05/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AER.psm1'

# Version number of this module.
ModuleVersion = '0.1.6'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'c9df382f-48f2-49b0-9136-98c9582c2b51'

# Author of this module
Author = 'Henderson Andrade (GitHub: @hendersonandrade) | Henrique Mizael (GitHub: @hmizael) | github.com/TrimTechBR, trimtech.github.io'

# Company or vendor of this module
CompanyName = 'TrimTechBR'

# Copyright statement for this module
Copyright = '(c) 2026. MIT License.'

# Description of the functionality provided by this module
Description = 'AER: Azure Estate Report is a PowerShell module that collects Azure Resource Manager and Azure Resource Graph data to generate structured HTML assessments of Azure environments. It helps cloud, platform, governance, security, FinOps, and operations teams document subscriptions, resources, diagnostic settings, observability coverage, governance posture, and operational metadata for architecture reviews, environment assessments, and cloud management reporting. It can also generate Excel and PDF reports.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    'Az.Accounts',
    'Az.ResourceGraph'
)

# Functions to export from this module
FunctionsToExport = @(
    'Invoke-AERReport'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess.
PrivateData = @{
    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'Azure',
            'Report',
            'Inventory',
            'Dashboard',
            'ResourceGraph',
            'HTML',
            'Assessment',
            'Observability',
            'Architecture',
            'Security'
        )

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/TrimTechBr/azure-estate-report/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/TrimTechBr/azure-estate-report'

        # A URL to an icon representing this module.
        # IconUri = ''

        # Release notes for this module.
        # ReleaseNotes = 'https://github.com/TrimTechBr/azure-estate-report'

        # Prerelease string of this module. Remove this line for stable releases.
        # Prerelease = 'alpha'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save.
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module.
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = 'https://trimtechbr.github.io'

# Default prefix for commands exported from this module.
# DefaultCommandPrefix = ''
}
